### ISSUE TITLE
Does this work for libraries that use stencil-state-tunnel?

### ISSUE THREAD

**Issue by sslotsky** [ionic-team/stencil-ds-plugins#10]
Our component library uses stencil-state-tunnel. When I use the react-output-target to build a React component library, the first component that gets defined in `components.ts` looks like this:

```ts
export const ContextConsumer = createReactComponent<JSX.ContextConsumer, HTMLContextConsumerElement>('context-consumer');
```

TypeScript is highlighting two errors here:

> Namespace 'LocalJSX' has no exported member 'ContextConsumer'

> Cannot find name 'HTMLContextConsumerElement'

And indeed, when I use 'Go to Definition', it takes me to the `dist/types/components.d.ts` file, where the word `Context` does not appear at all.

**Comment by jthoms1** [comment]
Good question. This is not something I have tried.  Can you provide a simple repo and I can dig in further?

**Comment by sslotsky** [comment]
Absolutely! Please see if you can generate React wrappers for this repo https://github.com/manifoldco/ui

This is what I tried:

```ts
  outputTargets: [
    reactOutputTarget({
      componentCorePackage: '@manifoldco/ui',
      proxiesFile: '../ui-react/src/components.ts',
    }),
    { type: 'dist' },
  ],
```

I have `@manifoldco/ui` installed in my `ui-react` folder. The only TypeScript errors I see are state-tunnel related.

**Comment by aharris** [comment]
I have having the same issue. After adding `stencil-state-tunnel` I can no longer build angular or react libraries.

**Comment by aharris** [comment]
Looking into it. It appears this is purposely being filtered out from the component types

```
const components = buildCtx.components.filter(m => !m.isCollectionDependency);

**Comment by aharris** [comment]
Looking into it. It appears this is purposely being filtered out from the component types

generate-app-types.ts
```
const components = buildCtx.components.filter(m => !m.isCollectionDependency);
```

This was introduced in commit `4553b3d8bdf13c94be30c8c2b0b25d66700d6835`

This makes sense as removing it causes the following issue:

```
[ ERROR ]  TypeScript: node_modules/@stencil/state-tunnel/dist/types/components.d.ts:24:13
           Interface 'HTMLContextConsumerElement' cannot simultaneously extend types
           'ContextConsumer' and 'ContextConsumer'.Named property ''subscribe'' of types
           'ContextConsumer' and 'ContextConsumer' are not identical.

     L24:    interface HTMLContextConsumerElement extends Components.ContextConsumer, HTMLStencilElement {}
     L25:    var HTMLContextConsumerElement: {
```

Not sure yet how to properly extend these types but maybe it will help point someone in the correct direction. Will post an update if i make progress.

**Comment by muskand** [comment]
Any updates here? Is the pull request being reviewed or merged any time soon?

**Comment by petermikitsh** [comment]
I was able to fix this build error by adding this:

```diff
  reactOutputTarget({
    componentCorePackage: 'component-library',
    proxiesFile: '../component-library-react/src/components.ts',
+   excludeComponents: ['context-consumer']
  }),
```

**Comment by jthoms1** [comment]
I would use the suggestion by @petermikitsh. Thanks!
