### ISSUE TITLE
angular-output-target not working with Angular 8

### ISSUE THREAD

**Issue by prenich-dil** [ionic-team/stencil-ds-plugins#18]
I'm a bit new with Angular so please excuse any ignorance on my part. From all my digging and experimenting, I cannot get Stencil with angular-output-target working with Angular 8. Neither have I seen any documentation or notes on what versions it is compatible with - considering how fast Angular has major version updates, this is unfortunate.

[This demo](https://github.com/ionic-team/stencil-ds-plugins-demo) uses Angular 7.2 and I am able to get that working correctly.

However, when I create a fresh install of Stencil, follow the documentation here and on the [demo template](https://github.com/ionic-team/stencil-ds-angular-template) to set up angular-output-target and try to use it with a fresh installation of Angular 8, the app breaks.

The error thrown is `NullInjectorError: No provider for ChangeDetectorRef`

I'm unfortunately not familiar enough with Angular to know enough about `ChangeDetectorRef` or why it would be failing within a v8 ecosystem. I'd love to help update the plugin to work with Angular 8, so hopefully all of this makes sense and someone can shed some light on the issues!

**Comment by robinsummerhill** [comment]
I can confirm that deploying the package to NPM fixed a similar problem that I was having. Thanks for the tip-off over on the Slack channel! It seems that using a local symlinked package was the cause of the problem.

**Comment by prenich-dil** [comment]
This issue does in fact turn out to be an issue with locally symlinked packages of Stencil (Angular output) projects vs remote NPM versions. As @robinsummerhill confirms, using the project as a proper remote package works fine (Thanks Robin! I never got around to testing that as we're still in heavy development)

To use a locally symlinked version of the Angular output Stencil, you need to set the `paths` TS configuration in the Angular app that is consuming the web components. Looks like when you symlink across to the Stencil package, it gets confused about where to find @Angular/* packages.

So, in the consuming Angular 8 app, in the `tsconfig` file, add this code under the `compilerOptions` object:
```
"paths": {
      "@angular/*": [
        "./node_modules/@angular/*"
      ]
    }
```
(Assuming that's where your Angular is installed)
