### ISSUE TITLE
Missing React component's data attributes 

### ISSUE THREAD

**Issue by biirus** [ionic-team/stencil-ds-plugins#25]
Thank you very much for this incredible work! Stencil is really awesome and allows us to unify our codebase for all projects!

But I noticed that generated React component can't have data attributes. 
I don't know, maybe this is already known issue and there is some plan or roadmap to fix this. 

Could you take a look on my PR, I believe it's able to fix this.
Thank you 🙏

**Comment by ehaynes99** [comment]
This will be very helpful. Data attributes are current swallowed by these wrappers, so components are practically impossible to test with `@testing-library`. JSDom isn't (currently) aware of the text inside of web components, so `getByText` and such don't work. `data-testid` and `aria-label` are the only suitable matchers.
