### ISSUE TITLE
React: StrictMode deprecations and SSR warnings

### ISSUE THREAD

**Issue by sslotsky** [ionic-team/stencil-ds-plugins#37]
Hello and thank you for this great plugin. It shows lots of promise for making web component libraries easier to consume from React. That said, I have observed a couple warnings I've encountered while trying to use the React components within React applications. 

[The library that I published is here](https://www.npmjs.com/package/@manifoldco/manifold-init-react) and is being used as follows:

```ts
import { ManifoldInit } from "@manifoldco/manifold-init-react/dist/components";

const Home = () => (
  <div className="container">
    <ManifoldInit env="stage" clientId="my-client-id" />
```

The app renders the component correctly but I've seen some warnings both in CRA and NextJS.

## CRA - StrictMode warning

When I use create-react-app I get the following warning in my browser console:

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of ManifoldInit which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in manifold-init (created by ManifoldInit)
    in ManifoldInit (created by ForwardRef(ManifoldInit))
    in ForwardRef(ManifoldInit) (at App.js:9)
    in div (at App.js:8)
    in App (at src/index.js:9)
    in StrictMode (at src/index.js:8)
```

I'd probably trace this to the `createReactComponent` which contains this in the cjs build:

```js
        componentDidUpdate(prevProps) {
            const node = ReactDom.findDOMNode(this);
            attachEventProps(node, this.props, prevProps);
        }
```

The component renders as it should for now but since `findDOMNode` is deprecated I expect that this will break in the future. Can this be updated to support StrictMode properly?

## SSR - Unhandled promise rejection

When I run my NextJS dev server, my terminal shows following error the first time I load the app:

```
(node:13529) UnhandledPromiseRejectionWarning: TypeError: head.querySelector is not a function
    at Object.bootstrapLazy (/home/sam/taco-cloud-react/node_modules/@manifoldco/manifold-init/dist/cjs/index-1ab6c73d.js:825:44)
    at /home/sam/taco-cloud-react/node_modules/@manifoldco/manifold-init/dist/cjs/loader.cjs.js:8:16
(node:13529) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13529) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I don't know if that's because NextJS is SSR and there's some code that shouldn't be running on the server side, but I tried rendering the component only when `process.browser` is defined and the error didn't go away, so it's hard to tell.

Again, the component renders fine on the page, but perhaps there are some places where SSR should be taken into account.

**Comment by jthoms1** [comment]
I have made some recent changes to the testing process for the ds-plugins. We have now integrated StrictMode into our tests. So any commits that cause a warning will now fail the tests. The findDOMNode warning has been fixed and will go out in the next release. I do not have a date yet, but I expect in the next couple weeks. The PR to cover this is below.

https://github.com/ionic-team/stencil-ds-plugins/pull/46

The SSR issue is another one entirely.  @sslotsky would you mind moving that part of the comment to another issue? Thanks!

**Comment by sslotsky** [comment]
> would you mind moving that part of the comment to another issue? Thanks!

Done @jthoms1, thanks for addressing the StrictMode warnings!
