### ISSUE TITLE
React - undefined event handlers should be ignored

### ISSUE THREAD

**Issue by ehaynes99** [ionic-team/stencil-ds-plugins#8]
In normal React components, the following is a no-op:

```javascript
<SomeComponent onSomeEvent={undefined} />
```

This is useful in cases where props are optional, or handlers are conditional for some other reason. E.g.
```javascript
const TestInput = ({ name, onBlur, onChange }) => (
  <input name={name} onBlur={onBlur} onChange={onChange} />
)
```
But will fail when used similarly with a wrapped stencil component if `onBlur` is not supplied:
```javascript
const TestInput = ({ name, onBlur, onChange }) => (
  <MyStencilInput name={name} onBlur={onBlur} onChange={onChange} />
)
// attachEventProps.js?9a31:67 Uncaught TypeError: Cannot read property 'call' of undefined
//    at HTMLElement.handler (attachEventProps.js?9a31:67)
```

The `addEventListener` call below should be wrapped in a `newEventHandler != null` check (or possibly even a `typeof newEventHandler === 'function'`)
https://github.com/ionic-team/stencil-ds-plugins/blob/1ed6161741d6210ebbe4def607a4d3532e804b8a/packages/react-output-target/react-component-lib/utils/attachEventProps.ts#L73

**Comment by jthoms1** [comment]
Mind making a PR to add the "!= null" check? I agree with the reasoning.
