### ISSUE TITLE
React: slot incompatibility

### ISSUE THREAD

**Issue by mkdorff** [ionic-team/stencil-ds-plugins#9]
When a Stencil component uses a slot and is not using the shadow DOM, the React component should be able to dynamically update the children it passes the component (as slotted elements) and not have it completely overwrite the internals of the Stencil component.

For example:
A Stencil component implemented as such:
```jsx
@Component({ tag: 'custom-button' })
export class CustomButton {
  render() {
    return (
      <button>
        <span>Pre-existing Content:</span>
        <slot />
      </button>
    );
  }
}
```

In React:
```jsx
import React, { useState } from "react";
import { CustomButton } from "../../components";

export default function ButtonWrapper() {
  const [buttonText, setButtonText] = useState('button text')
  return (
    <>
      <CustomButton>{buttonText}</CustomButton>
      <input value={buttonText} onChange={e => setButtonText(e.target.value)}></input>
    </>
  );
}
```

On initial render, the custom button's DOM looks like:
```html
<custom-button class="hydrated">
  <button>
    <span>Pre-existing Content:</span>
    <span class>button text</span>
  </button>
</custom-button>
```

When we update the value and thereby the slotted content that gets rendered inside the `<slot  />` in our custom button, the DOM looks like this:
```html
<custom-button class="hydrated">updated text</custom-button>
```
thereby wiping out the internal structure of our custom element.

I am aware that using shadow DOM is a possible remedy to this problem, however there are actual bugs in Google Chrome with shadow DOM that prevent us from completely adopting shadow DOM across the board.

**Comment by jthoms1** [comment]
Can you provide a simple repo with this issue and I will dig in further? Thank you!

**Comment by jthoms1** [comment]
Actually with some more thought I realized I missed something in the original issue.  React owns the entire DOM unless the nodes are in a shadow root. Every rerender will overwrite content.  It might be a possible to fix this with some logic around `shouldComponentUpdate` to prevent React from overwriting the DOM nodes.

If you look at all of the Ionic components if they do not use shadow then they have not child nodes other than slot.

**Comment by ehaynes99** [comment]
Out of curiosity, which bugs in Chrome?

React NEVER reads the DOM, only writes to it, so it has no direct awareness of anything below the outer tag. Short of hijacking the `children` property and directly manipulating the DOM in e.g. `componentDidUpdate` (or `useEffect` if this ever moves towards hooks), I don't see how really any nested content would be possible without the shadow root, nor does that seem like something that could be handled generically.

`shouldComponentUpdate` would just prevent the update of the button text. Also note:
https://reactjs.org/docs/react-component.html#shouldcomponentupdate

> This method only exists as a performance optimization. Do not rely on it to “prevent” a rendering, as this can lead to bugs.

and

> In the future React may treat shouldComponentUpdate() as a hint rather than a strict directive, and returning false may still result in a re-rendering of the component.
